server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user-b2b?createDatabaseIfNotExist=true
    username: root
    password: Chinmay@1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
